---
title: "git_00"
author: "Will Nicolai"
date: "Year 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
WITH saddest music all day long   
She soothed her secret sorrow:  
At night she sighed "I fear 'twas wrong   
Such cheerful words to borrow.  
Dearest, a sweeter, sadder song   
I'll sing to thee to-morrow."  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire   
I hold with those who favor fire.  
But if it had to perish twice,  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
 The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make   
The billows smooth and bright--  
And this was odd, because it was   
The middle of the night.  
  
The moon was shining sulkily,  
Because she thought the sun   
Had got no business to be there   
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!" 
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
When I consider every thing that grows   
Holds in perfection but a little moment,  
That this huge stage presenteth nought but shows   
Whereon the stars in secret influence comment;  
When I perceive that men as plants increase,  
Cheered and checked even by the self-same sky,  
Vaunt in their youthful sap, at height decrease,  
And wear their brave state out of memory;  
Then the conceit of this inconstant stay   
Sets you most rich in youth before my sight,  
Where wasteful Time debateth with decay   
To change your day of youth to sullied night,  
And all in war with Time for love of you,  
As he takes from you, I engraft you new.  
  